#!/bin/sh
#BT=`cat token.txt`
BT=`cat token2.txt`

curl -Ss -X GET https://mscr-test.2.rahtiapp.fi/datamodel-api/v2/frontend/mscrSearchPersonalContent --header 'Authorization: Bearer '$BT | jq -r '.hits.hits[]._source | [.id, .label.en, .status, .type ] |@tsv'
